# Generated by Django 3.2.16 on 2022-12-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='task_user',
        ),
    ]
